services:
  bot:
    build: .
    container_name: schedule_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:/app/database
      - ./bot.log:/app/bot.log

volumes:
  database:
